// <auto-generated />
using System;
using ItemCatalogService.Data.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ItemCatalogService.Data.Migrations
{
    [DbContext(typeof(ItemContext))]
    partial class ItemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("ItemCatalogService.Data.Adress", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ContactPersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SellerCompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StreetAdress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.HasIndex("ContactPersonId");

                    b.HasIndex("SellerCompanyId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ItemCatalogService.Data.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("ItemCatalogService.Data.ContactPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SellerCompanyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SellerCompanyId");

                    b.ToTable("ContactPeople");
                });

            modelBuilder.Entity("ItemCatalogService.Data.EMail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContactPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("EMailAdress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContactPersonId");

                    b.HasIndex("UserId");

                    b.ToTable("EMails");
                });

            modelBuilder.Entity("ItemCatalogService.Data.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("SellerCompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SellerCompanyId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ItemCatalogService.Data.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("ItemCatalogService.Data.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("RatingValue")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("ItemCatalogService.Data.SellerCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("SellerCompanies");
                });

            modelBuilder.Entity("ItemCatalogService.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ItemCatalogService.Data.Adress", b =>
                {
                    b.HasOne("ItemCatalogService.Data.ContactPerson", null)
                        .WithMany("WorkLocationAdresses")
                        .HasForeignKey("ContactPersonId");

                    b.HasOne("ItemCatalogService.Data.SellerCompany", null)
                        .WithMany("LocationAdresses")
                        .HasForeignKey("SellerCompanyId");
                });

            modelBuilder.Entity("ItemCatalogService.Data.Answer", b =>
                {
                    b.HasOne("ItemCatalogService.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ItemCatalogService.Data.ContactPerson", b =>
                {
                    b.HasOne("ItemCatalogService.Data.SellerCompany", null)
                        .WithMany("Contacts")
                        .HasForeignKey("SellerCompanyId");
                });

            modelBuilder.Entity("ItemCatalogService.Data.EMail", b =>
                {
                    b.HasOne("ItemCatalogService.Data.ContactPerson", null)
                        .WithMany("EMails")
                        .HasForeignKey("ContactPersonId");

                    b.HasOne("ItemCatalogService.Data.User", null)
                        .WithMany("EMails")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ItemCatalogService.Data.Item", b =>
                {
                    b.HasOne("ItemCatalogService.Data.SellerCompany", "SellerCompany")
                        .WithMany()
                        .HasForeignKey("SellerCompanyId");

                    b.Navigation("SellerCompany");
                });

            modelBuilder.Entity("ItemCatalogService.Data.Question", b =>
                {
                    b.HasOne("ItemCatalogService.Data.Item", null)
                        .WithMany("Questions")
                        .HasForeignKey("ItemId");

                    b.HasOne("ItemCatalogService.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ItemCatalogService.Data.Rating", b =>
                {
                    b.HasOne("ItemCatalogService.Data.Item", null)
                        .WithMany("Ratings")
                        .HasForeignKey("ItemId");

                    b.HasOne("ItemCatalogService.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ItemCatalogService.Data.ContactPerson", b =>
                {
                    b.Navigation("EMails");

                    b.Navigation("WorkLocationAdresses");
                });

            modelBuilder.Entity("ItemCatalogService.Data.Item", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("ItemCatalogService.Data.SellerCompany", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("LocationAdresses");
                });

            modelBuilder.Entity("ItemCatalogService.Data.User", b =>
                {
                    b.Navigation("EMails");
                });
#pragma warning restore 612, 618
        }
    }
}
