repo:
  - ./*
Data:
  - ./ItemCatalogService.Data
gRPCService:
  - ./ItemCatalogService.gRPCService
DataModel:
  - ./ItemCatalogService.Data/Models
DataAccess:
  - ./ItemCatalogService.Data/DataAccess
