repo:
  - ./*
Data:
  - ItemCatalogService.Data/*
gRPCService:
  - ItemCatalogService.gRPCService/*
DataModel:
  - ItemCatalogService.Data/Models/*
DataAccess:
  - ItemCatalogService.Data/DataAcces/*
Docker:
  - any: ["./*docker*", "./database.env", "ItemCatalogService.gRPCService/Dockerfile"]
